project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "BIOS 600 - Fall 2024"
  description: "Homepage for BIOS 600 - Principles of Statistical Inference, Fall 2024"
  site-url: "https://karamccor.github.io/b600-f24/"

  repo-url: https://karamccor.github.io/b600-f24/
  repo-actions: [edit, issue]

  open-graph: true

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    background: "#E4F1EE"

  sidebar:
    background: "#E4F1EE"
    logo: "images/logo_600.png"
    pinned: true
    align: center
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Course information"
        contents:
          - href: course-overview.qmd
            text: Overview
          - href: course-support.qmd
            text: Support
          - href: course-team.qmd
            text: Teaching team
          - href: index.qmd
            text: Schedule
      - section: "Project"
        contents:
          - href: project-description.qmd
            text: Description
          - href: project-tips-resources.qmd
            text: Tips + resources

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true

freeze: auto

editor: visual