---
title: "Lecture 4: Conditional Probability and Bayes' Rule"
subtitle: "BIOS 600 - Fall 2024"
author: "Kara McCormack"
logo: "images/logo_600.png"
format: 
  revealjs: 
    theme: slides.scss
    multiplex: true
    transition: fade
    slide-number: true
editor: visual
execute:
  freeze: auto
---

## Supplemental Reading

These readings are optional. All material in homework and exams will be covered in lecture and lab, and books do not cover everything we do in lecture (even if there is a corresponding section). 

However, for those with the very optional textbooks, the following sections correspond to today's lecture:

- Pagano and Gareau: Sections 6.2, 6.3
- OpenIntro Statistics: Section 3.2

## Overview

- Introduction to conditional probability
- Bayes' Rule

## Conditional probability

The probability an event will occur when another event has already occurred. The [conditional probability]{style="color: RosyBrown"} of event $A$ given event $B$ is

$$P(A|B) = \frac{P(A\cap B)}{P(B)}$$

Examples come up all the time in the real world:

- Given that a mammogram comes back positive, what is the probability that a woman has breast cancer?
- Given that a 68-year old man has suffered four previous heart attacks, what is the probability he dies in the next five years?
- Given that a patient has a mutation in the CFTR gene, what is the probability their offspring will have cystic fibrosis?

## Independence and the multiplicative rule {.smaller}

We can rewrite the definition of conditional probability:

$$P(A|B) = \frac{P(A\cap B)}{P(B)} \implies  \underbrace{P(A\cap B) = P(A | B) \times P(B)}_{\text{Multiplicative Rule}}$$

What does the multiplicative rule mean in plain English?

Events $A$ and $B$ are said to be [independent]{style="color: RosyBrown"} when 

$$P(A \cap B) = P(A) \times P(B)$$

or equivalently, $P(A|B) = P(A)$ or $P(B|A) = P(B)$

## Independent vs. disjoint events

## The law of total probability

## Bayes' rule

## Illustrating Bayes' rule


